# Reload the file with Prefix r.
bind r source-file ~/.tmux.conf \; display "Reloaded!"


# Set the default terminal mode to 256color mode.
#set -g default-terminal "screen-256color"

# Enable activity alerts.
setw -g monitor-activity on
set -g visual-activity on

set -g history-limit 100000

set -g status-style "bg=blue"

set -g mouse on

set -s set-clipboard on


bind C-d source-file ~/.config/tmux/session.tmux

