format="""\
$username\
$os\
$directory\
$git_commit\
$git_branch\
$git_status\
$git_state\
$python\
$status\
"""

[os]
disabled = false

[status]
format = '[$symbol$maybe_int]($style) '
disabled = false
success_symbol = '[❯](bold green)'
map_symbol = true
pipestatus = true

[git_commit]
disabled = false
tag_disabled = false
#only_detached = false

[python]
# Only use the `python3` binary to get the version.
python_binary = 'python3'

[username]
#show_always = true
format = "[$user]($style) "
